#!/usr/bin/env zsh


export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/data
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

export EDITOR=nvim
export VISUAL=nvim

export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export HISTFILE=$ZDOTDIR/zhistory
export HISTSIZE=1000
export SAVEHIST=10000

export OTHER=1
